apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d5iq7tnem-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d5iq7tnem-go 
  name: d5iq7tnem-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d5iq7tnem-go 
